### ISSUE TITLE
Could you give a little more instructions for setup for someone who does not know python.

### ISSUE THREAD

**Issue by emyrold** [Cobertos/md2notion#35]
Hello, I'm on mac and have several hundred markdown files with image directories that I would like to import into notion using your utility, just not sure where to start.

**Comment by Cobertos** [comment]
If the .md files have paths that point at the image files properly, you should just be able to use it with command line commands.

If not, then you would need to do something like the example found in the README, which shows how to pass an `imagePathFunc` to `upload()`, so that it can transform the paths to a file that is actually found. What sort of structure of .md/image files are you trying to upload?

**Comment by emyrold** [comment]
Hi,

Here is the path in the MD file, looks like Bears, either stores it in their database with URI encoded or the export runs it through some URI encoding.

![](JavaScript%20Understanding%20the%20Weird%20Parts%20%7C%20Udemy/Screen%20Shot%202018-03-22%20at%209.42.10%20PM.png)

Here is the folder path: /Users/emyrold/Desktop/Test-Export/JavaScript Understanding the Weird Parts | Udemy
Here is the file name: Screen Shot 2018-03-22 at 9.42.10 PM.png

I have the default Python 2.7 that comes with Mac OS X.

I do not know what setups steps I need to run your script.

Thanks for the reply!

-Erik

**Comment by Cobertos** [comment]
URL encoding is handled by the script.

Setup steps are in the README, see screenshot below:

![image](https://user-images.githubusercontent.com/6759176/120072383-a8209380-c061-11eb-857b-550c98a1f315.png)


You also need at least Python 3.6+ to run
